export const expenseCategories = [
  { label: 'Rent', value: 'Rent' },
  { label: 'Leases', value: 'Leases' },
  { label: 'Utilities', value: 'Utilities' },
  { label: 'Payroll', value: 'Payroll' },
  { label: 'Salaries', value: 'Salaries' },
  { label: 'Wages', value: 'Wages' },
  { label: 'Bonuses', value: 'Bonuses' },
  { label: 'Overtime', value: 'Overtime' },
  { label: 'Commissions', value: 'Commissions' },
  { label: 'Payroll Taxes', value: 'Payroll Taxes' },
  { label: 'Employee Benefits', value: 'Employee Benefits' },
  { label: 'Transport', value: 'Transport' },
  { label: 'Fuel & Mileage', value: 'Fuel & Mileage' },
  { label: 'Maintenance', value: 'Maintenance' },
  { label: 'Depreciation', value: 'Depreciation' },
  { label: 'Equipment & Furniture', value: 'Equipment & Furniture' },
  { label: 'Office Supplies', value: 'Office Supplies' },
  { label: 'Marketing', value: 'Marketing' },
  { label: 'Advertising', value: 'Advertising' },
  { label: 'Bank Charges', value: 'Bank Charges' },
  { label: 'Bank Fees', value: 'Bank Fees' },
  { label: 'Taxes', value: 'Taxes' },
  { label: 'Professional Fees', value: 'Professional Fees' },
  { label: 'Legal Fees', value: 'Legal Fees' },
  { label: 'Insurance', value: 'Insurance' },
  { label: 'IT & Software', value: 'IT & Software' },
  { label: 'Software Subscriptions', value: 'Software Subscriptions' },
  { label: 'Inventory Write-off', value: 'Inventory Write-off' },
  { label: 'Travel', value: 'Travel' },
  { label: 'Training', value: 'Training' },
  { label: 'Continuing Education', value: 'Continuing Education' },
  { label: 'Donations', value: 'Donations' },
  { label: 'Licenses & Permits', value: 'Licenses & Permits' },
  { label: 'Dues & Subscriptions', value: 'Dues & Subscriptions' },
  { label: 'Website Hosting/Maintenance', value: 'Website Hosting/Maintenance' },
  { label: 'Research & Development', value: 'Research & Development' },
  { label: 'Bad Debt', value: 'Bad Debt' },
  { label: 'Miscellaneous', value: 'Miscellaneous' }
];

export const paymentMethods = [
  { label: 'Cash', value: 'Cash' },
  { label: 'Bank Transfer', value: 'Bank Transfer' },
  { label: 'Credit Card', value: 'Credit Card' },
  { label: 'Mobile Money', value: 'Mobile Money' }
];
